### ISSUE TITLE
getOcrText http request detect "q" letter as "g" letter

### ISSUE THREAD

**Issue by chauhaidang** [jlipps/appium-ocr-plugin#10]
For some reason, the "q" letter on the screen is being detect as "g" and returned back from getOcrText command http request.

Appium inspector capture:
![image](https://github.com/jlipps/appium-ocr-plugin/assets/22814146/42aefee4-f4c5-48c7-90cc-bbb527274137)

Response from getOcrText
![image](https://github.com/jlipps/appium-ocr-plugin/assets/22814146/44338630-db50-4aab-9851-af43ab6d26c4)

Appium server log
![image](https://github.com/jlipps/appium-ocr-plugin/assets/22814146/2bc56ac5-fe63-4daf-99b3-83efb7a0b573)

**Comment by jlipps** [comment]
This is apparently how tesseract recognizes that character. The only thing I can recommend is to fiddle with the various tesseract settings to see if you can get it to work better. Perhaps not downsampling the screen would mean there's enough pixels for tesseract to better differentiate between 'g' and 'q'.

At any rate, there's nothing the plugin can do to help here.
