### ISSUE TITLE
Can not make example python-appium client work

### ISSUE THREAD

**Issue by DuongVu29** [jlipps/appium-ocr-plugin#2]
Dear Author,

I am trying to use this plugins, but I got error at "ExtendtionBase"class and "caps" argument in remote function, could you please help me out? besides, during starting appium, I tried thi --use-plugins=images, I saw the package was not activated, unless I tried --use-plugins=ocr. could you please kindly help?

Regards,
Dv

**Comment by jlipps** [comment]
hi, please attach your full appium log so i can see the error

**Comment by DuongVu29** [comment]
Dear Author,

please kindly find out the log while launching appium as below
<img width="569" alt="with --use-plugins=images" src="https://user-images.githubusercontent.com/26134104/191551061-6b39fd41-f902-4fbc-8de8-3ac4c59c4c11.png">

<img width="569" alt="with --use-plugins=images" src="https://user-images.githubusercontent.com/26134104/191551117-148cc0ea-c8a4-4dfc-81a1-7c9e48b4653c.png">

And I have the error while copy/paste the python example into GUI as below
<img width="640" alt="Screen Shot 2022-09-21 at 10 44 56 PM" src="https://user-images.githubusercontent.com/26134104/191551489-8aae75c2-1f4f-402a-8397-96992f556d7a.png">
I also post a request to appium using postman and get the result as below
<img width="819" alt="Screen Shot 2022-09-21 at 10 46 27 PM" src="https://user-images.githubusercontent.com/26134104/191551805-c75a7bae-e959-4374-98ed-c86e6e48ce05.png">

please let me know if you need any other information.

Regards,
Dv

**Comment by jlipps** [comment]
you used `--use-plugins=images`. that's not the name of the plugin, though. it should be `--use-plugins=ocr`. i've noticed this is a copy/paste error in the readme and will fix it.

**Comment by DuongVu29** [comment]
sorry, wrong log for launching with --use-plugins=ocr. here is the correct one
<img width="581" alt="with --use-plugin=ocr" src="https://user-images.githubusercontent.com/26134104/191554160-6b45c646-0f52-4fa0-9667-fe4d67f6571d.png">

**Comment by jlipps** [comment]
great, looks good!

**Comment by DuongVu29** [comment]
Dear Author,

how about the issue with python script?
as shown in the picture, there are errors with ExtensionBase in the class and "caps" argument in Driver.remote function. could you let me know how to solve it?
![image](https://user-images.githubusercontent.com/26134104/191659528-709727f2-8894-4040-8e2a-c227f8f79c94.png)

Regards,
Dv

**Comment by jlipps** [comment]
what does your IDE say the errors are?

**Comment by DuongVu29** [comment]
here is the error, please kindly advise. thanks 
![image](https://user-images.githubusercontent.com/26134104/192105299-225b1a47-bf8f-49f7-9a0d-a9dea7d9bda6.png)

Regards,
Dv

**Comment by DuongVu29** [comment]
the same error with "caps"

**Comment by jlipps** [comment]
the example code given in the readme was not intended to be functional on its own. but i have updated it so that it is more complete. it should give you an idea of how to fix the errors you have (obviously, if a variable is not defined it is not going to be functional)
