### ISSUE TITLE
Failed to parse image after screenshot

### ISSUE THREAD

**Issue by trungtran0195** [jlipps/appium-ocr-plugin#5]
Hi,

When I try to use the plugin today. I got this issue:

<img width="1240" alt="Screen Shot 2023-07-12 at 16 06 14" src="https://github.com/jlipps/appium-ocr-plugin/assets/59155920/907e7c5b-c215-4871-ab1b-7748a0d7f41d">

Report from terminal appium server:
`[debug] [XCUITestDriver@8a58 (126954df)] Encountered internal error running command: TypeError: support_1.imageUtil.getJimpImage is not a function
[debug] [XCUITestDriver@8a58 (126954df)]     at AppiumOcrPlugin.<anonymous> (/Users/test/.appium/node_modules/appium-ocr-plugin/src/index.ts:169:41)
[debug] [XCUITestDriver@8a58 (126954df)]     at Generator.next (<anonymous>)
[debug] [XCUITestDriver@8a58 (126954df)]     at fulfilled (/Users/test/.appium/node_modules/appium-ocr-plugin/build/index.js:5:58)
[debug] [XCUITestDriver@8a58 (126954df)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
`

I open the plugin and found that getJimpImage is not exist in image-utils
<img width="924" alt="Screen Shot 2023-07-12 at 17 45 44" src="https://github.com/jlipps/appium-ocr-plugin/assets/59155920/d36e3820-a566-48d5-a259-d6d0a6168cb1">

I am trying to resolve this myself but If you have any solution for this please help me.

Also I have no idea what should I include in params for POST API : /appium/ocr. I would be appreciated if you could give me a sample.

Thank you so much.

**Comment by jlipps** [comment]
Hmm, I may need to update this for the latest version of Appium.

**Comment by YhondriPM** [comment]
Hi, any progress with this?

**Comment by jlipps** [comment]
Yes I'm working on it. It's tricky because I'm replacing jimp with sharp and also upgraded a major version of webdriverio.

**Comment by jlipps** [comment]
@YhondriPM if you want you can pull this branch and try it out: https://github.com/jlipps/appium-ocr-plugin/pull/6

**Comment by jlipps** [comment]
actually just went ahead and published as 0.2
